### ISSUE TITLE
Chrome Store: Invalid manifest

### ISSUE THREAD

**Issue by xelobidid** [Arlodotexe/myTube-Companion#1]
I have an issue trying to install the extension from the Chrome store with the following message:

> An error has occurred
> There was a problem with the download. Please contact the developer or try again later.
> **Invalid manifest**

I'm currently on Chrome Version 69.0.3497.81 (Official Build) (64-bit)

**Comment by Arlodotexe** [comment]
This is a known issue. The Chrome Developer Dashboard does not tell me anything is wrong with the manifest when submitting the package, but upon installing, it gives this error. 

It will not tell me what is wrong with it the package. So to fix this, I will need to burn multiple version numbers to submit to the Chrome Web Store to test fixes with the manifest.

**Comment by xelobidid** [comment]
Ok!, so I downloaded version 0.1.5 from the dist folder to take a look at the manifest and in line 20 there's this:
`20: "{ENTER SIZE}": "/assets/BrowserAction.png"`
so I changed the "{ENTER SIZE}" for "48" (the size of the icon) and I'm able to install it in chrome via developer mode.

Edit:
there's also an error in line 59 saying: 
**Unrecognized manifest key '-ms-preload'.**

but it's working regardless of that error :D

**Comment by Arlodotexe** [comment]
This was on my todo list to check out tonight (I hadn't even looked at the manifest until I fixed this), since I need to also need to do a thing or two before I can finally publish the Microsoft Edge version of the extension.

Thank you! I'll get a fix published in an hour or so 😄

**Comment by Arlodotexe** [comment]
Update has been published to the store and I have verified that the issue is resolved.
