### ISSUE TITLE
Doesn't work on proper Firefox (pre-quantum disaster)

### ISSUE THREAD

**Issue by zakius** [Arlodotexe/myTube-Companion#3]
I am aware that these versions are not supported by Mozilla anymore nor are forks that keep up with security updates but many people (including me) can't give up on power Firefox used to bring to us so we won't be moving to quantum anytime soon.
Is is possible for you to provide classic version of this extension?

though tbh looking at the code quickly I don't see anything that wouldn't work in 56 so I don't know

**Comment by zakius** [comment]
Additional info: Chromium extension installed using Chrome Store Foxified seems to work

**Comment by Arlodotexe** [comment]
Interesting. I'll add this to the todo list and try to get an update out by the next release. I'll keep you posted

**Comment by Arlodotexe** [comment]
This should be working as of version 0.1.9

The reason it wasn't working before was that the official documentation is moving towards more modern programming APIs, which Firefox 56 doesn't support. 

Luckily I decided to unify all of the source code with the last update, and since most browsers still use the traditional stuff, Pre-Quantum should work like a charm.

**Comment by zakius** [comment]
I am aware of few fundamental differences between Webextensions and Chromium extensions (using browser object instead of chrome, using promises instead of callbacks) but FF provides also compatibility layer allowing developers to use chrome object and callbacks

as I said: I'm not sure what exactly was done in a way not supported by 56 but I'll probably look into it just out of my own curiosity

anyway: thank you for supporting us

**Comment by Arlodotexe** [comment]
My best guess is that Firefox 56 doesn't support JavaScript Promises, but you can still use callbacks on both Quantum and FF 56 (Which I what I'm doing now)

I'll go ahead and mark this issue as closed. Thanks for contributing!
