### ISSUE TITLE
Links to myTube app on Google says Redirect notice

### ISSUE THREAD

**Issue by maicol07** [Arlodotexe/myTube-Companion#4]
Hi,
all the links redirected to myTube on Google says Redirect notice. How to fix this? Maybe adding an option to disable auto redirect on all sites and/or only in specific sites?
Example of the error: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjAqqPhytPdAhUMxYUKHZZAAzoQwqsBMAB6BAgAEAQ&url=rykentube%3APlayVideo%3FID%3DFlsCjmMhFmw&usg=AOvVaw3aanyRxBSnCq55Jd72Wzbj

Thanks

**Comment by Arlodotexe** [comment]
This will be fixed in the next update! Thank you!

**Comment by Arlodotexe** [comment]
This bug has been fixed as of 1.2.0

**Comment by maicol07** [comment]
@Arlodotexe thanks theproblem is fixed on Google Search, but Google Images links aren't fixed...

**Comment by Arlodotexe** [comment]
Can you provide an example of this?

**Comment by maicol07** [comment]
Yes, here it is: https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=imgres&cd=&ved=2ahUKEwifprDrl9vdAhUIC-wKHRqfAkoQjxx6BAgBEAI&url=rykentube%3APlayVideo%3FID%3DFlsCjmMhFmw&psig=AOvVaw07Hb_SzGWzjHmxt_EwC6kG&ust=1538137766786602

Sorry for reply delay

**Comment by Arlodotexe** [comment]
I need to know how you got to this error message

**Comment by maicol07** [comment]
@Arlodotexe from this page, right-clicking the visit button or the video name.
https://www.google.com/search?q=youtube+rewind&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiz7_q41d3dAhXGVSwKHZk-BIwQ_AUIDCgD&biw=1920&bih=925#imgrc=CLkZOnWXuXXcYM:

**Comment by Arlodotexe** [comment]
Thank you @maicol07, I will push out a bug fixing update in the next couple days

**Comment by Arlodotexe** [comment]
This has been fixed as of version 1.2.2 (1.2.3 for Firefox)
