### ISSUE TITLE
[bug] Parsing Google authentication URLs

### ISSUE THREAD

**Issue by nirewen** [Arlodotexe/myTube-Companion#5]
**Issue**:
The extension is parsing Google's authentication URLs and opening in myTube

**Experienced in**:
Vivaldi (Chromium)

**Steps to reproduce**:
- Log out of your Google account (if you are logged in)
- Go to https://www.google.com
- Click Sign in button at the top-right corner

**Expected result**:
The tab shouldn't close itself and myTube shouldn't open

**Actual result**:
The tab is closing itself and myTube is opening

This might be related to #4

**Comment by ghost** [comment]
I'm also experiencing this issue.

**Comment by Arlodotexe** [comment]
This issue is fixed as of v1.3.3
